# Generated by Django 4.2.5 on 2023-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlindDateRecord',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('candidate_id', models.BigIntegerField(db_index=True, default=0, verbose_name='相亲对象id')),
                ('user_record', models.TextField(default='[]', verbose_name='自己的记录')),
                ('candidate_record', models.TextField(default='[]', verbose_name='对方的记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'blind_date_record',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(db_index=True, default=0, verbose_name='用户id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
